name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths:
      - '**.json'
  push:
    branches: [ master ]
    paths:
      - '**.json'

jobs:
  validate-jsons:
    name: Validate JSON files against schema
    runs-on: ubuntu-latest
    steps:

    - name: Install check-jsonschema
      run: pip install check-jsonschema

    - uses: actions/checkout@v7.0.0
      with:
        fetch-depth: 0

    - name: Validate schedule2 examples against schema2
      run: |
        check-jsonschema --schemafile validator/json/schema2.json \
          validator/json/examples/*-schedule2.json

    - name: Validate schedule1-json examples against schema1
      run: |
        check-jsonschema --schemafile validator/json/schema.json \
          validator/json/examples/pretalx-democon.json